import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AdminNavLink from "./components/AdminNavLink";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-950 text-neutral-50`}
      >
        <div className="min-h-screen flex flex-col">
          <header className="border-b border-neutral-800 bg-neutral-950/80 backdrop-blur sticky top-0 z-10">
            <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <div className="h-7 w-7 rounded-lg bg-gradient-to-br from-cyan-400 to-blue-600 flex items-center justify-center text-xs font-bold">
                  H
                </div>
                <div>
                  <div className="text-sm font-semibold tracking-tight">
                    Hemut Q&amp;A
                  </div>
                  <div className="text-[11px] text-neutral-400">
                    Real-time support dashboard
                  </div>
                </div>
              </div>
              <nav className="flex gap-3 text-xs font-medium text-neutral-300">
                <Link href="/forum" className="hover:text-white">
                  Forum
                </Link>
                <AdminNavLink />
                <Link href="/register" className="hover:text-white">
                  Register
                </Link>
              </nav>
            </div>
          </header>
          <main className="flex-1">
            <div className="max-w-5xl mx-auto px-4 py-6">{children}</div>
          </main>
          <footer className="border-t border-neutral-800 text-[11px] text-neutral-500 py-3 text-center">
            Hemut Trial Project &middot; Real-time Q&amp;A Dashboard
          </footer>
        </div>
      </body>
    </html>
  );
}
